name: Dread Knight Combat Training
automation:
  - type: counter
    counter: Blood Fury
    amount: "0"
    allowOverflow: false
    errorBehaviour: raise
  - type: target
    target: self
    effects:
      - type: ieffect2
        name: Dread Knight Training
        duration: null
        effects: null
        attacks: []
        buttons:
          - label: Offense Stance
            automation:
              - type: target
                target: self
                effects:
                  - type: ieffect2
                    name: Offense Training
                    duration: null
                    effects: null
                    attacks: []
                    buttons:
                      - label: Change Stance
                        automation:
                          - type: remove_ieffect
                        verb: decides to Change Stance
                        style: "4"
                        defaultDC: null
                        defaultAttackBonus: null
                        defaultCastingMod: null
                    end: false
                    conc: false
                    desc: null
                    stacking: false
                    save_as: null
                    parent: dkt
                  - type: text
                    text: >-
                      While in this stance, you deal an additional amount of  damage with your
                      melee weapon equal to the number of Fury Points you
                      currently possess (minimum of 1).

                      Apply by adding the snippet `dkc` to your attack.
                    title: Offense
            verb: assumes their Offensive Stance
            style: "4"
            defaultDC: null
            defaultAttackBonus: null
            defaultCastingMod: null
          - label: Defense Stance
            automation:
              - type: counter
                counter: Blood Fury
                amount: "0"
                allowOverflow: false
                errorBehaviour: warn
              - type: variable
                name: bfc
                value: lastCounterRemaining
                onError: "1"
              - type: variable
                name: bf
                value: max(floor(bfc/2), 1)
              - type: target
                target: self
                effects:
                  - type: ieffect2
                    name: Defense Training
                    duration: null
                    effects:
                      ac_bonus: bf
                    attacks: []
                    buttons:
                      - label: Change Stance
                        automation:
                          - type: remove_ieffect
                        verb: decides to Change Stance
                        style: "4"
                        defaultDC: null
                        defaultAttackBonus: null
                        defaultCastingMod: null
                    end: false
                    conc: false
                    desc: Current bonus of {bf)}
                    stacking: false
                    save_as: null
                    parent: dkt
                  - type: text
                    text: While in this stance, you gain a bonus to your AC equal to half the number
                      of Fury Points you currently possess (minimum of 1).
                    title: Defense
            verb: assumes their Defensive Stance
            style: "1"
            defaultDC: null
            defaultAttackBonus: null
            defaultCastingMod: null
          - label: Precise Stance
            automation:
              - type: target
                target: self
                effects:
                  - type: ieffect2
                    name: Precision Training
                    duration: null
                    effects: null
                    attacks: []
                    buttons:
                      - label: Change Stance
                        automation:
                          - type: remove_ieffect
                        verb: decides to Change Stance
                        style: "4"
                        defaultDC: null
                        defaultAttackBonus: null
                        defaultCastingMod: null
                    end: false
                    conc: false
                    desc: null
                    stacking: false
                    save_as: null
                    parent: dkt
                  - type: text
                    text: >-
                      While in this stance, you gain a bonus to hit with your weapon attacks
                      equal to half the number of Fury Points you currently
                      possess (minimum of 1).

                      Apply by adding the `dkc` snippet to your attack.


                      Additionally, you may use Dexterity instead of Strength for the attack and damage rolls of any melee weapon with the slashing damage type.

                      To use this bonus add `dex` after the `dkc` snippet.
                    title: Accuracy
            verb: assumes their Precise Stance
            style: "3"
            defaultDC: null
            defaultAttackBonus: null
            defaultCastingMod: null
          - label: Leave Stance
            automation:
              - type: remove_ieffect
            verb: decides to leave their stances
            style: "2"
            defaultDC: null
            defaultAttackBonus: null
            defaultCastingMod: null
        end: false
        conc: false
        desc: You become trained in the martial ways of the Dread Knights. As a bonus
          action, you may enter, exit, or change combat stances.
        stacking: false
        save_as: dkt
        parent: null
  - type: text
    text: >-
      You become trained in the martial ways of the Dread Knights. As a bonus
      action, you may enter, exit, or change combat stances. While in a combat
      stance, you gain the features of that stance.


      **Offensive.** While in this stance, you deal an additional amount of  damage with your melee weapon equal to the number of Fury Points you currently possess (minimum of 1).


      **Defense.** While in this stance, you gain a bonus to your AC equal to half the number of Fury Points you currently possess (minimum of 1).


      **Accuracy.** While in this stance, you gain a bonus to hit with your weapon attacks equal to half the number of Fury Points you currently possess (minimum of 1).

      Additionally, you may use Dexterity instead of Strength for the attack and damage rolls of any melee weapon with the slashing damage type.
    title: Dread Knight Combat Training
_v: 2
proper: true
verb: uses their
activation_type: 3




#End YAML dump. Attached snippet for the action:

!snippet dkc <drac2>
ch = character()
cc = "Blood Fury"
args = argparse(&ARGS&)

if not ch.cc_exists(cc):
  return f""" -f "You are not a Vampire!" """

bf = ch.get_cc(cc)
if c:=combat():
  if c.me:
    if effect:=c.me.get_effect("Offense Training"):
      bonus = max(1,bf)
      return f""" -d {bonus} -f "**Offensive Training**|While in this stance, you deal an additional amount of  damage with your melee weapon equal to the number of Fury Points you currently possess (minimum of 1, currently +{bonus})." """

    elif effect:=c.me.get_effect("Precision Training") and args.get("dex"):
      bonus = max(1,floor(bf/2))
      dbonus = dexterityMod-strengthMod
      return f""" -b {bonus} -b {dbonus} -d {dbonus} -f "**Accuracy Stance**|While in this stance, you gain a bonus to hit with your weapon attacks equal to half the number of Fury Points you currently possess (minimum of 1, currently +{bonus}).
Additionally, you may use Dexterity instead of Strength for the attack and damage rolls of any melee weapon with the slashing damage type (currently +{dbonus})." """

    elif effect:=c.me.get_effect("Precision Training"):
      bonus = max(1,floor(bf/2))
      return f""" -b {bonus} -f "**Accuracy Stance**|While in this stance, you gain a bonus to hit with your weapon attacks equal to half the number of Fury Points you currently possess (minimum of 1, currently +{bonus})." """
</drac2>
